<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,intial-scale=1">
    <meta http-equiv="X-UA-Comptible" content="IE=edge">
	<title>LMS</title>
  <link rel="shortcut icon" type="image/png" href="img/scales-of-justice-icon-512-244111.png">
	<link rel="stylesheet" href="css/bootstrap.min.css">
	<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="css/law.css">
	<script src="js/jquery.min.js"></script>
	</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">
<div>
<nav class="navbar navbar-default navbar-fixed-top navbar-expand-sm">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand text-light">LMS</a> 
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>                        
			</button>
		</div>
		<div class="collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav navbar-right">
				<li>
                <div class="dropd">
                        <button class="dropdbtn">CASE</button>
                        <div class="dropd-content">
                            <a href="addcase.php" class="a_drop">ADD CASE</a>
                            <a href="currentcase.php" class="a_drop">CURRENT CASE</a>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="dropd">
                        <button class="dropbtn" onclick="location.href='clogout.php';" type="button">LOG OUT</button>
                    </div>
                </li>
			</ul>
		</div>
	</div>
</nav>

</div>
<div class="container-fluid">
  <div class="row">
      <h1 style="font-family:arial;"><b>CRIMINAL LAW</b></h1>
    <div class="col-sm-4">
       <img style="max-width:400px; margin-top: 25px;"
        src="img/34094504-strafrecht-woord-wolk-concept.jpg">
    </div>  
    <div class="col-sm-8">
      <h3>Criminal law is the body of law that relates to crime.
 It proscribes conduct perceived as threatening, harmful, 
 or otherwise endangering to the property, health, safety, and moral welfare of people inclusive of one's self.
 Most criminal law is established by statute, which is to say that the laws are enacted by a legislature.
 Criminal law includes the punishment and rehabilitation of people who violate such laws.</h3>
      <h3>Criminal law varies 
 according to jurisdiction, and differs from civil law, where emphasis is more on dispute resolution and victim
 compensation than on punishment or rehabilitation. Criminal procedure is a formalized official activity that authenticates
 the fact of commission of a crime and authorizes punitive or rehabilitative treatment of the offender.</h3>
      
    </div>
	
  </div>
  <div class="row">
  <h2 style="font-family:arial;"><b>Types of criminal offenses</b></h2>
    
      <h4>Although there are many different kinds of crimes, criminal acts can generally be divided into four 
          primary categories: personal crimes, property crimes, inchoate crimes,
           statutory crimes, and financial crimes.</h4>
        <div class="col-sm-8">
           <h3>Personal Crimes -</h3>
        <h4>“Offenses against the Person”: These are crimes that
            result in physical or mental harm to another person. Personal crimes include:</h4>
            <ul style="list-style-type: circle;">
                <li>Assault - an intentional act that causes a fear of imminent harmful or offensive touching.
                    An assault can occur even if the contact never occurs. 
                    Since the act must be intentional, an accidental action won't amount to an assault</li>
                <li>
                Battery - crime defined as the unlawful or unauthorized application of force to another person,
                 resulting in contact that is either harmful or offensive to the victim.
                 The crime of battery is usually connected with the crime of assault, which is an incomplete or attempted battery.    
            </li>
            <li>
            False Imprisonment
                </li>
                <li>
                Kidnapping
                </li>
                <li>
                Homicide – crimes such as first and second degree, murder, and involuntary manslaughter, and vehicular homicide
                </li>
                <li>
                Rape, statutory rape, sexual assault and other offenses of a sexual nature
            </li>
            </ul>
            </div>
            <div class="col-sm-4"><br><br>
                <img style="max-width:400px; margin-top: 25px;"
                    src="img/500_F_175891991_DOtzUw44wPfEICL6bfjlq0ETI3oeFV7J.jpg">
                </div>
        <div class="col-sm-8">
        <h3>Property Crimes -</h3>
        <h4>Property crimes typically involve interference with the property of another. 
            Although they may involve physical or mental harm to another, they primarily result in the 
            deprivation of the use or enjoyment of property. Many property crimes are theft crimes, including
            burglary, larceny, robbery, auto theft, and shoplifting</h4>
        </div>
        <div class="col-sm-4">
                <img style="max-width:250px; margin-top: 25px;"
                    src="img/robber-mask-carries-bag-thief-robs-house-property-insurance-illustration-vector-format-63403511.jpg">
                </div>
        <div class="col-sm-8">
            <h3>Inchoate Crimes -</h3>
        <h4>Inchoate crimes refer to those crimes that were initiated but not completed,
             and acts that assist in the commission of another crime. Inchoate crimes require more than a
              person simply intending or hoping to commit a crime. Rather, the individual must take a “substantial step”
               towards the completion of the crime in order to be found guilty. Inchoate crimes include aiding and 
               abetting, attempt, and conspiracy. In some cases, inchoate crimes can be punished to the same degree that 
               the underlying crime would be punished, while in other cases, the punishment might be less severe.</h4>
        </div>
        <div class="col-sm-4">  
        <img style="max-width:300px; margin-top: 25px;"
                    src="img/crime-scene-25252141.jpg">
                </div>
        <div class="col-sm-8">
        <h3>Statutory Crimes -</h3>
        <h4>Statutory crimes include those crimes, in addition to the crimes discussed above,
             which are proscribed by statute. Three significant types of statutory crimes are alcohol related crimes,
              drug crimes, traffic offenses, and financial/white collar crimes. These crimes are specifically prohibited by
               statute because society hopes to deter individuals from engaging in them. Alcohol-related crimes include a
                variety of offenses regarding how and where alcohol can be consumed, such as:</h4>
            <ul style="list-style-type: circle;">
                <li>    
                Driving Under the Influence (DUI/OWI/DWI) - 
                Driving Under the Influence (DUI) is a crime under state laws that seek to regulate the operation of a 
                vehicle after a driver has consumed alcohol. DUIs typically make it illegal for a driver who has had more
                 than a certain amount of alcohol to get behind the wheel of a car. DUIs are also referred to as driving while
                  intoxicated (DWI) or operating while intoxicated (OWI). A DUI is a criminal offense with serious criminal 
                  and civil penalties.
                </li>
                <li>
                Open Contaiuner Voilations - Open container laws are defined as laws that limit or prohibit the possession 
                of open containers of alcohol in public areas.
                </li>
                <li>
                    Minor in possession of Alcohol -
                    Minor in possession of alcohol laws criminalize the possession and consumption of alcohol by individuals
                     who are under the legal drinking age. The purpose of these laws is to strictly punish underage drinkers and
                      deter illegal alcohol consumption.
                </li>
                <li>
                        underage DUI -
                        Like a standard DUI, an underage DUI criminalizes the actions of a driver 
                        who gets behind the wheel of a vehicle after having too much to drink. However,
                         underage DUIs specifically target drivers who are under the age of 21 and have
                          committed the dual offenses of illegal consumption of alcohol and driving while intoxicated. 
                          Since underage drunk drivers are particularly dangerous, they are subject to strict laws and penalties.
                </li>
        <li>    
        Boating DUI - 
        States criminalize DUIs because cars are very powerful vehicles that can cause serious harm to others if the 
        driver is incapacitated. For the same reason, operating a watercraft or boat while intoxicated is held to be 
        a very dangerous crime, also known as a BUI. BUIs are the cause of an increasing number of fatal and non-fatal 
        injuries that occur on the water.    
    </li>
    </ul>
</div>
<div class="col-sm-4"><br><br><br><br><br>
<img style="max-width:400px; margin-top: 25px;"
                    src="img/cocaine-drug-addiction-lines-one-hundred-dollars-banknote-black-background-closeup-82739297.jpg">
                </div>
    <div class="col-sm-8">
    <h3>Financial and Other Crimes</h3>
    <h4>
    Finally, financial crimes often involve deception or fraud for financial gain. Although white-collar`
     crimes derive their name from the corporate officers who historically perpetrated them, anyone in any industry
      can commit a white-collar crime. These crimes include many types of fraud and blackmail, embezzlement and money
       laundering, tax evasion, and cybercrime.
    </h4>
    </div>
    <div class="col-sm-4">
    <img style="max-width:350px; margin-top: 25px;"
                    src="img/metallic-handcuffs-money-financial-crime-concept-metallic-handcuffs-money-financial-crime-concept-140361071.jpg">
                </div>
</div>
	
  </div> 
</div>



</body>
</html>